language: node_js

node_js:
  - "lts/*"

install:
  - git clone git@github.com:imdreamrunner/litst.git
  - cd litst
  - npm install
  - npm run build
  - npm link
  -- cd ..

script:
  - litst publish ./pages --output ./publish

deploy:
  provider: pages
  local-dir: publish
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
